<<<<<<< HEAD
# Generated by Django 3.2.25 on 2025-05-08 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='essay',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='supporting_documents',
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('under_review', 'Under Review')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
=======
# Generated by Django 3.2.25 on 2025-05-08 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='essay',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='supporting_documents',
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('under_review', 'Under Review')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
>>>>>>> ce448217a3e986c12530c8704b3356fc81cc687d
